server:
  port: 8080
spring:
#数据源
  datasource:
      name: mysql_test
      url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 1234
    #  type: org.apache.commons.dbcp2.BasicDataSource
      dbcp2:
        driver-class-name: com.mysql.jdbc.Driver
        max-idle: 0
        max-total: 100
        max-wait-millis: 10000
        #事务隔离级别
        default-transaction-isolation: 4
      type: com.zaxxer.hikari.HikariDataSource
#thymeleaf
  thymeleaf:
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
#数据库实体
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQLDialect
  data:
  #elasticSearch
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
  #jedis配置
  redis:
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 2000
        min-idle: 5
    host: 47.94.208.1
    port: 6379
    password: zxx1994
    timeout: 1000

  application:
    name: server
#mybatis 配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.blog.user.entity

